### ISSUE TITLE
On non-snap Firefox the window decorations vanish and I need to press alt to view them

### ISSUE THREAD

**Issue by millionsofplayers** [soup-bowl/Modoki-Firefox#13]
[Image of the issue](https://imgur.com/zK5PItS.png)

**Comment by millionsofplayers** [comment]
solved, forgot to toggle on "title bar"

**Comment by soup-bowl** [comment]
No worries. Menu bar and CSD/title bar switched on are hard dependencies currently. Former due to a shim that helps to keep the tab bar on the bottom, other because I want to retain the original theme aesthetic.
