### ISSUE TITLE
Every button uses the whole toolbar picture 

### ISSUE THREAD

**Issue by 111ebobo** [soup-bowl/Modoki-Firefox#15]

**Comment by soup-bowl** [comment]
Replicated in a development environment in Firefox 112 and above. This appears to be a change in upstream Firefox, as the spritemap is distributed using -moz-image-region which appears to no longer work in the current configuration.

![image](https://user-images.githubusercontent.com/11209477/233866928-79f87511-31b9-497e-be22-2adbab8e1d97.png)

I'll put in a warning on the frontpage until it's fixed.
