### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by realepikool** [soup-bowl/Modoki-Firefox#20]

**Comment by soup-bowl** [comment]
Looks like they renamed "Profile Directory" to "Profile Folder".

You can thank Firefox for making the process difficult.

**Comment by realepikool** [comment]
oh, alright, thank you. i found it. i put the ZIP file into the Chrome folder and restarted it, yet, it didnt work for me for some reason.

**Comment by realepikool** [comment]
alright. i found it. i put the ZIP file into the Chrome folder and restarted it, yet, it didnt work for me for some reason.

**Comment by realepikool** [comment]
> Looks like they renamed "Profile Directory" to "Profile Folder". This might also differ due to language variations.
> 
> You can thank Firefox for making the process difficult.

?

**Comment by realepikool** [comment]
> Looks like they renamed "Profile Directory" to "Profile Folder". This might also differ due to language variations.
> 
> You can thank Firefox for making the process difficult.

nvm i got it 2 work
