### ISSUE TITLE
Interface not fully visible

### ISSUE THREAD

**Issue by juppes2** [soup-bowl/Modoki-Firefox#21]
![Auswahl_061](https://github.com/soup-bowl/Modoki-Firefox/assets/53827706/516dd278-5e62-4edb-8e13-096056a6311a)
![Auswahl_062](https://github.com/soup-bowl/Modoki-Firefox/assets/53827706/5d4bee75-e8b2-4bce-a91c-7527d67a2593)
### What version of the theme are you using?

Latest Version (0.6)

### What edition of Firefox are you on?

Mainline Firefox

### Please describe the problem you are experiencing. Screenshots very welcome.

Hello,
first of all: thank you for this great "revival" of a beautiful vintage Firefox theme. I installed it, and it just looks great. I am not a great fan of the actual Firefox themes, and so I am really happy to have stumbled upon good old Modoki here. 
My Firefox runs under Linux Mint 21.2 Cinnamon (just in case this is of any relevance to the issue here).
There are two things worth mentioning here:
1. In the symbol bar you cannot fully see the 'Hamburger' menu button. It's cut off in the middle regardless of Firefox being windowed or full-screen.
2. You can only see the 'New Tab' button if there are less than 7 tabs open. Of course CTRL+T still works, but this seems to have to to with the fact that the tabs are never narrowed when you add a new one. So after more than 6 tabs, the bar is 'overflowing' so to speak.

Is there, maybe, a fix for this behaviour? I attach two screenshots below.

**Comment by soup-bowl** [comment]
Glad you like the theme and thank you for contributing your environment. This has been reported already as #8, and has not been fixed yet (but a workaround has been suggested).

**Comment by juppes2** [comment]
Thank you for the hint pointing me to #8 . I followed the instructions I found there, and it works here, too. The result is something you can live with, but I hope that one day you will find the time ro fix the code, so no tinkering will be necessary any more.
![Auswahl_063](https://github.com/soup-bowl/Modoki-Firefox/assets/53827706/64b19c83-c407-4a79-b926-0d2a88648351)
