### ISSUE TITLE
Tabs not highlighting

### ISSUE THREAD

**Issue by AliVe52** [soup-bowl/Modoki-Firefox#24]
### What version of the theme are you using?

Latest Version (0.6)

### What edition of Firefox are you on?

Mainline Firefox

### Please describe the problem you are experiencing. Screenshots very welcome.

![image](https://github.com/soup-bowl/Modoki-Firefox/assets/25278145/7b87c62b-173d-4395-9fd7-aad151bcd452)

As you can see, the active tab is not highlighted...

**Comment by soup-bowl** [comment]
Thanks for the report - looks like a change in how the selected state is handled, will deal with later.

**Comment by soup-bowl** [comment]
Fixed in 0.7
