### ISSUE TITLE
Address bar popup alignment issues on Nightly

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/Modoki-Firefox#29]
Spotted on Nightly 126:

<img width="977" alt="Screenshot 2024-04-15 at 1 25 52 PM" src="https://github.com/soup-bowl/Modoki-Firefox/assets/11209477/784d61b1-8a08-4f4b-945a-e7366696c7da">

Might also be a good time to deal with the fact the background of the URL bar is no longer white (not visible in the screenshot due to the bug).

**Comment by soup-bowl** [comment]
This is in Developer already - I'm not going to be able to locate and fix this in time before it ends up in mainline Firefox.

I've added a note to the readme to indicate this.

Side note: Anyone aware if Firefox publishes their styling changes anywhere?

**Comment by Fettuc20** [comment]
Got an answer from the wonderful people at Reddit.
Find your urlbar.css, then delete or comment line #64 and add this corrected line:

> #urlbar[breakout-extend] {
        /* top:calc((var(--urlbar-toolbar-height) - var(--urlbar-height)) / 2) !important; */
        top:calc((var(--urlbar-container-height) - var(--urlbar-height)) / 2) !important;
        left:calc((var(--urlbar-continer-width) - var(--urlbar-width)) / 2) !important;
        width:100% !important }

**Comment by soulhotel** [comment]
Yo!I saw the Reddit post as well. I've yet to find any documentation of what exactly Mozilla did, but to keep it brief: they renamed some selectors/variables, and perhaps removed some that could be seen as duplicates (doing the same thing). Don't even know every selector thats been effected, but in your case:

toolbars.css, line 93
- :-moz-lwtheme is no longer recognized, use [lwtheme] or [lwtheme="true"]
- i didnt check to see if you have it again in your theme, but if you do ^

urlbar.css, line 64+ (credit to [ResurgamS13](https://www.reddit.com/user/ResurgamS13/))
- the variable `--urlbar-toolbar-height` is no longer recognized, replaced with `--urlbar-container-height`
- line 88, you have border-top removed for the urlbarView, im unsure if the update broke the spacing between the view and the search bar, but adding it back created a more consistent look for now.

tabs.css, line 107
- added a height to the outmost tab container, for consistency

I could be missing some things, but your theme seems functional after doing these things above.

Ive [forked your repo](https://github.com/soulhotel/Modoki-Firefox/tree/main/IE6/chrome), so you can compare. All changes above are labeled with `*new` comments. Tested on 127.0b6 in system Dark Mode, using Firefoxs built in light theme.  Whenever you verify the 'fixes' I can delete the fork. 

![YbXseBuuqy](https://github.com/soup-bowl/Modoki-Firefox/assets/155501797/dfe2330f-a81b-4c41-8939-351a7517c345)

**Comment by soup-bowl** [comment]
Thank you both for the information on this ([dropped a thanks to the Reddit thread too](https://www.reddit.com/r/FirefoxCSS/comments/1d1tccv/modoki_modern_url_bar_problem/)). Thank you for all the information provided on how I can resolve this. I'll take a look this week and see about patching this in.

(for my notes, from the Reddit thread - this was possibly caused by [Bug 1889463](https://bugzilla.mozilla.org/show_bug.cgi?id=1889463)).

**Comment by soup-bowl** [comment]
Regarding:

> * :-moz-lwtheme is no longer recognized, use [lwtheme] or [lwtheme="true"]

Good point on this one - I had *a lot* of cover-all references in `icons.css`. I've added them to my changes.

**Comment by soup-bowl** [comment]
Thanks all - 0.9 (and latest) should now have this fixed. I'll need to dedicate some time to repositioning, but at least for now the theme is back to being usable now.
