### ISSUE TITLE
Tabs are ELONGATED in height in FF 103

### ISSUE THREAD

**Issue by cherwally** [soup-bowl/Modoki-Firefox#5]
I tested this theme on a old FF 88 and looks fine,
but updating on last stable version reveals a new bug.
The tables are **ELONGATED in height** compared with the whole tab bar.
Neither reactivating the toolbar compact mode wouldn't make any notable difference.
Here a screenshot on dark theme +compact mode activated (unsupported)
[https://imgur.com/2WSAwdd](https://imgur.com/2WSAwdd)
Afaik FF changed the UI to Proton i think on the last releases, 
this can be the culprit.
Any chance for a quick update fix?

**Comment by soup-bowl** [comment]
Weird, I wasn't notified that this was left on here.

If you're still using this theme, which I'm guessing 2 months later you're probably not, are you still experiencing this bug with the latest main changes?

I can't recall what changed between now and when you'd submitted this, but some tab changes have definitely occurred since then (and it's now been tested on FF 105) which might've since resolved it.

Also I don't currently support dark mode. This will be dealt with, but isn't a focus since dark mode wasn't a concern in the theme this was based on.

**Comment by philberthfz** [comment]
I can confirm that this issue exists on Firefox 108 on Ubuntu. It's only a minor issue in compact mode, but if you dare use normal or even touch mode it becomes very distracting.

Compact:
![Compact](https://user-images.githubusercontent.com/36530111/209453989-a6ee657e-b67f-4687-ad6c-d2789383c3e7.png)

Normal:
![Normal](https://user-images.githubusercontent.com/36530111/209453990-aa84c8ca-78e5-4927-804c-5561e50f38af.png)

Touch:
![Touch](https://user-images.githubusercontent.com/36530111/209453991-f806e0b3-aabc-4f10-a2c1-feadbe227213.png)

When bookmarks bar is disabled, the navbar buttons are partially overlapped by the tab bar.
![When bookmarks bar is disabled, navbar buttons are overlapped](https://user-images.githubusercontent.com/36530111/209453992-85266a00-341b-487e-85fb-880cf6084623.png)

From what experimentation I've done so far, I've identified two possible things that could be done to address the issue.

1) In toolbars.css, give #tabbrowser-tabs the max-height property and set it to match #TabsToolbar max-height property. This method looks good, but only if you're using compact mode - attempting to use any other mode results in above behavior.

2) Also in toolbars.css, you can simply remove the max-height property from #TabsToolbar. You get the extra chunky tabs that firefox is using nowadays, but nothing overlaps. 

3) I suppose also you could do both. Setting max-height on #tabbrowser-tabs  to 27px and removing the max-height property from #TabsToolbar. This allows for the compact mode to be perfectly sized without overlaps, while allowing the tab bar and tabs to become bigger on normal and touch densities. This feels like the most elegant solution, but I haven't extensively tested it so your mileage may vary. This is the solution I personally am using.

Oh, it goes without saying but I haven't tested this on mac or windows, so it could completely break over there or something. Works fine on Ubuntu though!

**Comment by soup-bowl** [comment]
Thanks for your extensive research @philberthfz, it’s very much appreciated, once I return from the festive break I’ll have a look into patching it following your discoveries.

MacOS compatibility is not supported currently, so the fix working on Windows and Linux is perfect enough until I can find a way to test the theme on MacOS.
